language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - nightly

notifications:
  email: false

matrix:
  allow_failures:
    - julia: nightly
    - julia: 1.0
    - julia: 1.1

# before_install:

script:
  - julia --project -e 'import Pkg; Pkg.build(); Pkg.test("RPTrees"; coverage=true)'

# After successful build submit coverage report and deploy updated documentation
# But limit deployment to the linux worker so this is done only once.
after_success:
  # Install required packages for coverage
  - julia --project -e 'using Pkg; Pkg.add("Coverage");'

  # Install pacakges for documentation
  # - julia --project -e 'import Pkg; Pkg.add("Documenter"); Pkg.add("DocumenterTools");'

  # Submit test coverage report
  - julia --project -e 'using Coverage; Codecov.submit(Codecov.process_folder())'

  # Build and deploy documentation
  # - julia --project ./docs/make.jl
